
var game_file_list = [
    //以下为自动修改，请勿修改
    //----auto game_file_list start----
	"libs/modules/egret/egret.js",
	"libs/modules/egret/egret.native.js",
	"libs/modules/eui/eui.js",
	"libs/modules/res/res.js",
	"libs/modules/game/game.js",
	"libs/modules/tween/tween.js",
	"bin-debug/commont/BaseUI.js",
	"bin-debug/game/pk/pkCommont/EnemyHeadItem.js",
	"bin-debug/game/pk/pkMain/PKResultBase.js",
	"bin-debug/game/pk/pkMain/PKItemBig.js",
	"bin-debug/commont/MyTool.js",
	"bin-debug/commont/MyWindow.js",
	"bin-debug/commont/Net.js",
	"bin-debug/commont/skin/BasePanel.js",
	"bin-debug/commont/skin/BookBG.js",
	"bin-debug/commont/ui/AlertUI.js",
	"bin-debug/commont/ui/ConfirmUI.js",
	"bin-debug/commont/ui/ResourceUI.js",
	"bin-debug/commont/ui/TipsUI.js",
	"bin-debug/commont/ui/TopUI.js",
	"bin-debug/commont/ui/TouchTipsUI.js",
	"bin-debug/commont/VScrollerGroup.js",
	"bin-debug/db/MainGameVO.js",
	"bin-debug/db/MonsterSkillVO.js",
	"bin-debug/db/MonsterVO.js",
	"bin-debug/db/PropVO.js",
	"bin-debug/debug/DebugInput.js",
	"bin-debug/debug/DebugSkillItem.js",
	"bin-debug/debug/DebugSkillList.js",
	"bin-debug/debug/DebugUI.js",
	"bin-debug/debug/ScrollTest.js",
	"bin-debug/game/bag/PropManager.js",
	"bin-debug/game/collect/CollectItem.js",
	"bin-debug/game/collect/CollectManager.js",
	"bin-debug/game/collect/CollectUI.js",
	"bin-debug/game/common/AwardItem.js",
	"bin-debug/game/common/AwardUI.js",
	"bin-debug/game/common/HelpItem.js",
	"bin-debug/game/common/HelpUI.js",
	"bin-debug/game/dayTask/DayTaskItem.js",
	"bin-debug/game/dayTask/DayTaskUI.js",
	"bin-debug/game/draw/DrawItem.js",
	"bin-debug/game/draw/DrawResultUI.js",
	"bin-debug/game/draw/DrawUI.js",
	"bin-debug/game/friend/FriendAddItem.js",
	"bin-debug/game/friend/FriendAddUI.js",
	"bin-debug/game/friend/FriendListItem.js",
	"bin-debug/game/friend/FriendListUI.js",
	"bin-debug/game/friend/FriendLogItem.js",
	"bin-debug/game/friend/FriendManager.js",
	"bin-debug/game/friend/FriendPKItem.js",
	"bin-debug/game/friend/FriendSearchUI.js",
	"bin-debug/game/friend/FriendTalkItem.js",
	"bin-debug/game/friend/FriendTalkUI.js",
	"bin-debug/game/friend/SendTalkUI.js",
	"bin-debug/game/honor/HonorItem.js",
	"bin-debug/game/honor/HonorManager.js",
	"bin-debug/game/honor/HonorSortItem.js",
	"bin-debug/game/honor/HonorUI_bak.js",
	"bin-debug/game/honor/HonorUI.js",
	"bin-debug/game/mainPage/MainDayItem.js",
	"bin-debug/game/mainPage/MainHeadItem.js",
	"bin-debug/game/mainPage/MainMainItem.js",
	"bin-debug/game/mainPage/MainMapItem.js",
	"bin-debug/game/mainPage/MainPageItem.js",
	"bin-debug/game/mainPage/MainPageUI.js",
	"bin-debug/game/mainPage/MainServerEqualItem.js",
	"bin-debug/game/mainPage/MainServerItem.js",
	"bin-debug/game/mainPage/TopPlayerTips.js",
	"bin-debug/game/map/MapData.js",
	"bin-debug/game/map/MapExchangeUI.js",
	"bin-debug/game/map/MapGameUI.js",
	"bin-debug/game/map/MapInfoUI.js",
	"bin-debug/game/map/MapItem.js",
	"bin-debug/game/map/MapMainUI.js",
	"bin-debug/game/map/MapManager.js",
	"bin-debug/game/map/MapShopBuyUI.js",
	"bin-debug/game/map/MapShopItem.js",
	"bin-debug/game/map/MapShopUI.js",
	"bin-debug/game/map/MapUI.js",
	"bin-debug/game/monster/MonsterInfoBase.js",
	"bin-debug/game/monster/MonsterInfoBaseItem.js",
	"bin-debug/game/monster/MonsterList.js",
	"bin-debug/game/monster/MonsterManager.js",
	"bin-debug/game/monster/MonsterSendStarUI.js",
	"bin-debug/game/monster/MonsterSendTalkUI.js",
	"bin-debug/game/monster/MonsterTalkItem.js",
	"bin-debug/game/monster/MonsterTalkUI.js",
	"bin-debug/game/pk/dayGame/DayGameManager.js",
	"bin-debug/game/pk/dayGame/DayGameUI.js",
	"bin-debug/game/pk/dayGame/DayLogItem.js",
	"bin-debug/game/pk/dayGame/DayLogMoreUI.js",
	"bin-debug/game/pk/dayGame/DayLogUI.js",
	"bin-debug/game/pk/friendGame/FriendPKAskUI.js",
	"bin-debug/game/pk/friendGame/FriendPKManager.js",
	"bin-debug/game/pk/friendGame/FriendPKViewUI.js",
	"bin-debug/game/pk/mainGame/MainAwardBeforeUI.js",
	"bin-debug/game/pk/mainGame/MainGameManager.js",
	"bin-debug/game/pk/mainGame/MainGameUI.js",
	"bin-debug/game/pk/mainGame/MyCardGroupUI.js",
	"bin-debug/game/pk/mainGame/MyCardTaskUI.js",
	"bin-debug/AssetAdapter.js",
	"bin-debug/game/pk/pkCommont/MyHeadItem.js",
	"bin-debug/game/pk/pkCommont/PKTool.js",
	"bin-debug/game/pk/pkDress/PKDressChooseItem.js",
	"bin-debug/game/pk/pkDress/PKDressChooseListItem.js",
	"bin-debug/game/pk/pkDress/PKDressChooseUI.js",
	"bin-debug/game/pk/pkDress/PKDressEnemyItem.js",
	"bin-debug/game/pk/pkDress/PKDressSimpleItem.js",
	"bin-debug/game/pk/pkDress/PKDressUI.js",
	"bin-debug/game/pk/pkMain/PKEmoItem.js",
	"bin-debug/game/pk/pkMain/PKFailUI.js",
	"bin-debug/game/pk/pkMain/PKItem.js",
	"bin-debug/game/pk/pkMain/PKItem2.js",
	"bin-debug/commont/Config.js",
	"bin-debug/game/pk/pkMain/PKLoadingUI.js",
	"bin-debug/game/pk/pkMain/PKMainHp.js",
	"bin-debug/game/pk/pkMain/PKMainMV.js",
	"bin-debug/game/pk/pkMain/PKMainUI.js",
	"bin-debug/game/pk/pkMain/PKMainUI2.js",
	"bin-debug/game/pk/pkMain/PKManager.js",
	"bin-debug/commont/GameEvent.js",
	"bin-debug/game/pk/pkMain/PKResultGroup.js",
	"bin-debug/game/pk/pkMain/PKResultItem.js",
	"bin-debug/game/pk/pkMain/PKResultItem2.js",
	"bin-debug/game/pk/pkMain/PKResultItem3.js",
	"bin-debug/game/pk/pkMain/PKResultItem4.js",
	"bin-debug/game/pk/pkMain/PKResultMVP.js",
	"bin-debug/game/pk/pkMain/PKResultMVPItem.js",
	"bin-debug/game/pk/pkMain/PKResultUI.js",
	"bin-debug/game/pk/pkMain/PKTalkItem.js",
	"bin-debug/game/pk/pkMain/PKWinUI.js",
	"bin-debug/game/pk/serverGame/ServerGameManager.js",
	"bin-debug/game/pk/serverGame/ServerGameUI.js",
	"bin-debug/game/pk/serverGameEqual/ServerGameEqualManager.js",
	"bin-debug/game/pk/serverGameEqual/ServerGameEqualUI.js",
	"bin-debug/game/pk/vedio/PlayerVO.js",
	"bin-debug/game/pk/vedio/VideoCode.js",
	"bin-debug/game/pk/vedio/VideoDetailUI.js",
	"bin-debug/game/pk/vedio/VideoGuide.js",
	"bin-debug/game/pk/vedio/VideoGuideItem.js",
	"bin-debug/game/pk/vedio/VideoHpItem.js",
	"bin-debug/game/pk/vedio/VideoInfoUI.js",
	"bin-debug/game/pk/vedio/VideoItem.js",
	"bin-debug/game/pk/vedio/VideoItem3.js",
	"bin-debug/game/pk/vedio/VideoManager.js",
	"bin-debug/game/pk/vedio/VideoMonsterItem.js",
	"bin-debug/game/pk/vedio/VideoMV.js",
	"bin-debug/game/pk/vedio/VideoPlayUI.js",
	"bin-debug/game/pk/vedio/VideoStatItem.js",
	"bin-debug/game/pk/vedio/VideoTopStatItem.js",
	"bin-debug/game/pk/vedio/VideoUI.js",
	"bin-debug/game/rank/RankItem.js",
	"bin-debug/game/rank/RankManager.js",
	"bin-debug/game/rank/RankUI.js",
	"bin-debug/game/shop/PayManager.js",
	"bin-debug/game/shop/ShopItem.js",
	"bin-debug/game/shop/ShopItem2.js",
	"bin-debug/game/shop/ShopUI.js",
	"bin-debug/game/teamDungeon/common/CreateTeamUI.js",
	"bin-debug/game/teamDungeon/common/InviteTeamItem.js",
	"bin-debug/game/teamDungeon/common/InviteTeamUI.js",
	"bin-debug/game/teamDungeon/common/TeamDungeonAwardBoxItem.js",
	"bin-debug/game/teamDungeon/common/TeamDungeonGameUI.js",
	"bin-debug/game/teamDungeon/common/TeamInfoUI.js",
	"bin-debug/game/teamDungeon/TeamDungeonItem.js",
	"bin-debug/game/teamDungeon/TeamDungeonMain.js",
	"bin-debug/game/teamDungeon/TeamDungeonManager.js",
	"bin-debug/game/teamDungeon/teamPVE/TeamPVEMain.js",
	"bin-debug/game/teamDungeon/teamPVE/TeamPVEMainItem.js",
	"bin-debug/game/teamDungeon/teamPVE/TeamPVEManager.js",
	"bin-debug/game/tec/TecManager.js",
	"bin-debug/game/user/GameLogUI.js",
	"bin-debug/game/user/MyInfoUI.js",
	"bin-debug/game/user/OtherInfoUI.js",
	"bin-debug/game/user/SettingUI.js",
	"bin-debug/game/user/UserChangeWordUI.js",
	"bin-debug/guide/GuideManager.js",
	"bin-debug/guide/GuideUI.js",
	"bin-debug/LoadingUI.js",
	"bin-debug/login/ChangeHeadUI.js",
	"bin-debug/login/ChooseServerItem.js",
	"bin-debug/login/ChooseServerUI.js",
	"bin-debug/login/HeadItem.js",
	"bin-debug/login/LoginMainPageUI.js",
	"bin-debug/login/LoginManager.js",
	"bin-debug/login/LoginServerUI.js",
	"bin-debug/login/LoginUI.js",
	"bin-debug/login/RegisterServerUI.js",
	"bin-debug/login/RegisterUI.js",
	"bin-debug/Main.js",
	"bin-debug/MainLoadingUI.js",
	"bin-debug/manager/AniManager.js",
	"bin-debug/manager/AppManager.js",
	"bin-debug/manager/CacheManager.js",
	"bin-debug/manager/DebugManager.js",
	"bin-debug/manager/DragManager.js",
	"bin-debug/manager/EgretManager.js",
	"bin-debug/manager/EventManager.js",
	"bin-debug/manager/FromManager.js",
	"bin-debug/manager/GameManager.js",
	"bin-debug/manager/HelpManager.js",
	"bin-debug/manager/RedPointManager.js",
	"bin-debug/manager/SharedObjectManager.js",
	"bin-debug/manager/SoundManager.js",
	"bin-debug/manager/SyncManager.js",
	"bin-debug/manager/TimeManager.js",
	"bin-debug/manager/UserManager.js",
	"bin-debug/MsgingUI.js",
	"bin-debug/ThemeAdapter.js",
	"bin-debug/util/ArrayUtil.js",
	"bin-debug/util/BadWords.js",
	"bin-debug/util/BadWordsFilter.js",
	"bin-debug/util/Base64.js",
	"bin-debug/util/DateUtil.js",
	"bin-debug/util/LoadingFile.js",
	"bin-debug/util/LoadingQueue.js",
	"bin-debug/util/md5.js",
	"bin-debug/util/NumberUtil.js",
	"bin-debug/util/ObjectUtil.js",
	"bin-debug/util/PopUpManager.js",
	"bin-debug/util/ShapeObject.js",
	"bin-debug/util/StringUtil.js",
	//----auto game_file_list end----
];

var window = {};

egret_native.setSearchPaths([""]);

egret_native.requireFiles = function () {
    for (var key in game_file_list) {
        var src = game_file_list[key];
        require(src);
    }
};

egret_native.egretInit = function () {
    egret_native.requireFiles();
    egret.TextField.default_fontFamily = "/system/fonts/DroidSansFallback.ttf";
    //egret.dom为空实现
    egret.dom = {};
    egret.dom.drawAsCanvas = function () {
    };
};

egret_native.egretStart = function () {
    var option = {
        //以下为自动修改，请勿修改
        //----auto option start----
		entryClassName: "Main",
		frameRate: 30,
		scaleMode: "fixedWidth",
		contentWidth: 640,
		contentHeight: 960,
		showPaintRect: false,
		showFPS: false,
		fpsStyles: "x:0,y:0,size:30,textColor:0x00c200,bgAlpha:0.9",
		showLog: false,
		logFilter: "",
		maxTouches: 2,
		textureScaleFactor: 1
		//----auto option end----
    };

    egret.native.NativePlayer.option = option;
    egret.runEgret();
    egret_native.Label.createLabel(egret.TextField.default_fontFamily, 20, "", 0);
    egret_native.EGTView.preSetOffScreenBufferEnable(true);
};